<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Android Phones - Category 7
            [
                'sku' => 'SAMS23U-BLK-256',
                'barcode' => '8806094693737',
                'name' => 'Samsung Galaxy S23 Ultra 256GB',
                'description' => 'Flagship smartphone with 200MP camera, S Pen, Snapdragon 8 Gen 2',
                'category_id' => 7,
                'supplier_id' => 1,
                'brand' => 'Samsung',
                'model' => 'SM-S918B',
                'cost_price' => 55000.00,
                'selling_price' => 69999.00,
                'markup_percentage' => 27.27,
                'tax_rate' => 12.00,
                'stock_quantity' => 15,
                'reorder_level' => 5,
                'max_stock_level' => 30,
                'unit_of_measure' => 'piece',
                'weight' => 0.234,
                'dimensions' => '163.4 x 78.1 x 8.9 mm',
                'image_url' => '/images/products/s23-ultra.jpg',
                'is_active' => true,
                'is_serialized' => true,
                'warranty_period' => 12,
            ],
            [
                'sku' => 'XIA13P-BLU-128',
                'barcode' => '6941812735961',
                'name' => 'Xiaomi 13 Pro 128GB',
                'description' => 'Premium flagship with Leica camera, Snapdragon 8 Gen 2, 120Hz AMOLED',
                'category_id' => 7,
                'supplier_id' => 3,
                'brand' => 'Xiaomi',
                'model' => 'M2210132G',
                'cost_price' => 38000.00,
                'selling_price' => 49999.00,
                'markup_percentage' => 31.58,
                'tax_rate' => 12.00,
                'stock_quantity' => 22,
                'reorder_level' => 8,
                'max_stock_level' => 40,
                'unit_of_measure' => 'piece',
                'weight' => 0.229,
                'dimensions' => '162.9 x 74.6 x 8.4 mm',
                'image_url' => '/images/products/13-pro.jpg',
                'is_active' => true,
                'is_serialized' => true,
                'warranty_period' => 12,
            ],
            [
                'sku' => 'REALGT3-GRN-256',
                'barcode' => '6941399059696',
                'name' => 'Realme GT 3 256GB',
                'description' => 'Gaming phone with 240W fast charging, RGB lighting, Snapdragon 8+ Gen 1',
                'category_id' => 7,
                'supplier_id' => 5,
                'brand' => 'Realme',
                'model' => 'RMX3662',
                'cost_price' => 21000.00,
                'selling_price' => 27999.00,
                'markup_percentage' => 33.33,
                'tax_rate' => 12.00,
                'stock_quantity' => 18,
                'reorder_level' => 6,
                'max_stock_level' => 35,
                'unit_of_measure' => 'piece',
                'weight' => 0.199,
                'dimensions' => '163.1 x 75.3 x 8.5 mm',
                'image_url' => '/images/products/gt3.jpg',
                'is_active' => true,
                'is_serialized' => true,
                'warranty_period' => 12,
            ],

            // iPhones - Category 8
            [
                'sku' => 'IPH15PM-BLK-512',
                'barcode' => '194253426172',
                'name' => 'iPhone 15 Pro Max 512GB',
                'description' => 'Apple flagship with A17 Pro chip, titanium design, 48MP camera',
                'category_id' => 8,
                'supplier_id' => 2,
                'brand' => 'Apple',
                'model' => 'A3105',
                'cost_price' => 72000.00,
                'selling_price' => 89990.00,
                'markup_percentage' => 25.00,
                'tax_rate' => 12.00,
                'stock_quantity' => 8,
                'reorder_level' => 3,
                'max_stock_level' => 15,
                'unit_of_measure' => 'piece',
                'weight' => 0.221,
                'dimensions' => '159.9 x 76.7 x 8.25 mm',
                'image_url' => '/images/products/iphone-15-pro-max.jpg',
                'is_active' => true,
                'is_serialized' => true,
                'warranty_period' => 12,
            ],
            [
                'sku' => 'IPH14-BLU-128',
                'barcode' => '194253381839',
                'name' => 'iPhone 14 128GB',
                'description' => 'Previous gen iPhone with A15 Bionic, dual camera system',
                'category_id' => 8,
                'supplier_id' => 2,
                'brand' => 'Apple',
                'model' => 'A2882',
                'cost_price' => 38000.00,
                'selling_price' => 49990.00,
                'markup_percentage' => 31.55,
                'tax_rate' => 12.00,
                'stock_quantity' => 12,
                'reorder_level' => 4,
                'max_stock_level' => 20,
                'unit_of_measure' => 'piece',
                'weight' => 0.172,
                'dimensions' => '146.7 x 71.5 x 7.8 mm',
                'image_url' => '/images/products/iphone-14.jpg',
                'is_active' => true,
                'is_serialized' => true,
                'warranty_period' => 12,
            ],

            // Laptops - Category 10
            [
                'sku' => 'DELL-XPS15-I9',
                'barcode' => '884116395584',
                'name' => 'Dell XPS 15 i9 32GB 1TB',
                'description' => 'Premium laptop with 4K OLED display, Intel i9-13900H, RTX 4060',
                'category_id' => 10,
                'supplier_id' => 9,
                'brand' => 'Dell',
                'model' => 'XPS 9530',
                'cost_price' => 105000.00,
                'selling_price' => 139999.00,
                'markup_percentage' => 33.33,
                'tax_rate' => 12.00,
                'stock_quantity' => 5,
                'reorder_level' => 2,
                'max_stock_level' => 10,
                'unit_of_measure' => 'piece',
                'weight' => 1.92,
                'dimensions' => '344.7 x 230.1 x 18 mm',
                'image_url' => '/images/products/dell-xps-15.jpg',
                'is_active' => true,
                'is_serialized' => true,
                'warranty_period' => 24,
            ],
            [
                'sku' => 'LEN-YOGA7-R7',
                'barcode' => '196804259819',
                'name' => 'Lenovo Yoga 7 Ryzen 7 16GB',
                'description' => '2-in-1 convertible laptop with touchscreen, AMD Ryzen 7 7730U',
                'category_id' => 10,
                'supplier_id' => 10,
                'brand' => 'Lenovo',
                'model' => '82YN001SPH',
                'cost_price' => 48000.00,
                'selling_price' => 64999.00,
                'markup_percentage' => 35.42,
                'tax_rate' => 12.00,
                'stock_quantity' => 10,
                'reorder_level' => 3,
                'max_stock_level' => 15,
                'unit_of_measure' => 'piece',
                'weight' => 1.49,
                'dimensions' => '314.4 x 225.8 x 17.9 mm',
                'image_url' => '/images/products/yoga-7.jpg',
                'is_active' => true,
                'is_serialized' => true,
                'warranty_period' => 12,
            ],

            // Tablets - Category 12
            [
                'sku' => 'IPAD-AIR5-BLU-256',
                'barcode' => '194253082743',
                'name' => 'iPad Air 5th Gen 256GB WiFi',
                'description' => 'iPad Air with M1 chip, 10.9-inch Liquid Retina display',
                'category_id' => 12,
                'supplier_id' => 2,
                'brand' => 'Apple',
                'model' => 'A2588',
                'cost_price' => 38000.00,
                'selling_price' => 49990.00,
                'markup_percentage' => 31.55,
                'tax_rate' => 12.00,
                'stock_quantity' => 14,
                'reorder_level' => 5,
                'max_stock_level' => 25,
                'unit_of_measure' => 'piece',
                'weight' => 0.461,
                'dimensions' => '247.6 x 178.5 x 6.1 mm',
                'image_url' => '/images/products/ipad-air.jpg',
                'is_active' => true,
                'is_serialized' => true,
                'warranty_period' => 12,
            ],

            // Phone Cases - Category 13
            [
                'sku' => 'CASE-S23U-CLR',
                'barcode' => '8806094693744',
                'name' => 'Samsung S23 Ultra Clear Case',
                'description' => 'Official clear protective case for Galaxy S23 Ultra',
                'category_id' => 13,
                'supplier_id' => 8,
                'brand' => 'Samsung',
                'model' => 'EF-QS918CTEGWW',
                'cost_price' => 450.00,
                'selling_price' => 999.00,
                'markup_percentage' => 122.00,
                'tax_rate' => 12.00,
                'stock_quantity' => 85,
                'reorder_level' => 20,
                'max_stock_level' => 150,
                'unit_of_measure' => 'piece',
                'weight' => 0.035,
                'dimensions' => '170 x 80 x 10 mm',
                'image_url' => '/images/products/s23u-case.jpg',
                'is_active' => true,
                'is_serialized' => false,
                'warranty_period' => null,
            ],
            [
                'sku' => 'CASE-IPH15-SIL',
                'barcode' => '194253421658',
                'name' => 'iPhone 15 Silicone Case',
                'description' => 'Apple silicone case with MagSafe',
                'category_id' => 13,
                'supplier_id' => 8,
                'brand' => 'Apple',
                'model' => 'MT0Y3ZM/A',
                'cost_price' => 1200.00,
                'selling_price' => 2999.00,
                'markup_percentage' => 149.92,
                'tax_rate' => 12.00,
                'stock_quantity' => 65,
                'reorder_level' => 15,
                'max_stock_level' => 100,
                'unit_of_measure' => 'piece',
                'weight' => 0.030,
                'dimensions' => '160 x 75 x 8 mm',
                'image_url' => '/images/products/iph15-case.jpg',
                'is_active' => true,
                'is_serialized' => false,
                'warranty_period' => null,
            ],

            // Screen Protectors - Category 14
            [
                'sku' => 'TGLASS-UNIV-6.7',
                'barcode' => '4895241101234',
                'name' => 'Tempered Glass 6.7 inch Universal',
                'description' => '9H hardness tempered glass screen protector',
                'category_id' => 14,
                'supplier_id' => 8,
                'brand' => 'Generic',
                'model' => 'TG-6.7',
                'cost_price' => 85.00,
                'selling_price' => 299.00,
                'markup_percentage' => 251.76,
                'tax_rate' => 12.00,
                'stock_quantity' => 200,
                'reorder_level' => 50,
                'max_stock_level' => 300,
                'unit_of_measure' => 'piece',
                'weight' => 0.015,
                'dimensions' => '160 x 75 x 1 mm',
                'image_url' => '/images/products/tempered-glass.jpg',
                'is_active' => true,
                'is_serialized' => false,
                'warranty_period' => null,
            ],

            // Chargers & Cables - Category 15
            [
                'sku' => 'CHARGE-USBC-65W',
                'barcode' => '6941399057982',
                'name' => 'USB-C 65W Fast Charger',
                'description' => 'GaN fast charger with USB-C PD 3.0',
                'category_id' => 15,
                'supplier_id' => 8,
                'brand' => 'Ugreen',
                'model' => 'CD226',
                'cost_price' => 650.00,
                'selling_price' => 1499.00,
                'markup_percentage' => 130.62,
                'tax_rate' => 12.00,
                'stock_quantity' => 110,
                'reorder_level' => 30,
                'max_stock_level' => 200,
                'unit_of_measure' => 'piece',
                'weight' => 0.120,
                'dimensions' => '65 x 65 x 30 mm',
                'image_url' => '/images/products/usbc-charger.jpg',
                'is_active' => true,
                'is_serialized' => false,
                'warranty_period' => 12,
            ],
            [
                'sku' => 'CABLE-USBC-2M',
                'barcode' => '6941399054273',
                'name' => 'USB-C to USB-C Cable 2m',
                'description' => '100W USB-C cable with braided nylon',
                'category_id' => 15,
                'supplier_id' => 8,
                'brand' => 'Anker',
                'model' => 'A8856',
                'cost_price' => 250.00,
                'selling_price' => 699.00,
                'markup_percentage' => 179.60,
                'tax_rate' => 12.00,
                'stock_quantity' => 150,
                'reorder_level' => 40,
                'max_stock_level' => 250,
                'unit_of_measure' => 'piece',
                'weight' => 0.045,
                'dimensions' => '200 x 10 x 8 cm',
                'image_url' => '/images/products/usbc-cable.jpg',
                'is_active' => true,
                'is_serialized' => false,
                'warranty_period' => 18,
            ],

            // Power Banks - Category 16
            [
                'sku' => 'PBANK-ANK-20K',
                'barcode' => '194644086015',
                'name' => 'Anker PowerCore 20000mAh',
                'description' => '20000mAh power bank with 18W fast charging',
                'category_id' => 16,
                'supplier_id' => 8,
                'brand' => 'Anker',
                'model' => 'A1268',
                'cost_price' => 1200.00,
                'selling_price' => 2499.00,
                'markup_percentage' => 108.25,
                'tax_rate' => 12.00,
                'stock_quantity' => 45,
                'reorder_level' => 15,
                'max_stock_level' => 80,
                'unit_of_measure' => 'piece',
                'weight' => 0.365,
                'dimensions' => '158 x 74 x 19 mm',
                'image_url' => '/images/products/anker-20k.jpg',
                'is_active' => true,
                'is_serialized' => false,
                'warranty_period' => 18,
            ],

            // Wireless Earbuds - Category 20
            [
                'sku' => 'AIRPODS-PRO2-WHT',
                'barcode' => '194253397427',
                'name' => 'AirPods Pro 2nd Gen',
                'description' => 'Premium wireless earbuds with active noise cancellation and spatial audio',
                'category_id' => 20,
                'supplier_id' => 2,
                'brand' => 'Apple',
                'model' => 'MTJV3',
                'cost_price' => 11500.00,
                'selling_price' => 14990.00,
                'markup_percentage' => 30.35,
                'tax_rate' => 12.00,
                'stock_quantity' => 28,
                'reorder_level' => 10,
                'max_stock_level' => 50,
                'unit_of_measure' => 'piece',
                'weight' => 0.050,
                'dimensions' => '60.6 x 45.2 x 21.7 mm',
                'image_url' => '/images/products/airpods-pro2.jpg',
                'is_active' => true,
                'is_serialized' => true,
                'warranty_period' => 12,
            ],
            [
                'sku' => 'XIAOMI-BUDS4-BLK',
                'barcode' => '6934177781315',
                'name' => 'Xiaomi Buds 4 Pro',
                'description' => 'True wireless earbuds with ANC and Hi-Res audio',
                'category_id' => 20,
                'supplier_id' => 3,
                'brand' => 'Xiaomi',
                'model' => 'M2212E1',
                'cost_price' => 4500.00,
                'selling_price' => 6999.00,
                'markup_percentage' => 55.53,
                'tax_rate' => 12.00,
                'stock_quantity' => 35,
                'reorder_level' => 12,
                'max_stock_level' => 60,
                'unit_of_measure' => 'piece',
                'weight' => 0.048,
                'dimensions' => '55 x 55 x 25 mm',
                'image_url' => '/images/products/buds4-pro.jpg',
                'is_active' => true,
                'is_serialized' => false,
                'warranty_period' => 12,
            ],

            // Smart Watches - Category 18
            [
                'sku' => 'APWATCH-S9-45',
                'barcode' => '194253406754',
                'name' => 'Apple Watch Series 9 45mm',
                'description' => 'Advanced smartwatch with health monitoring and fitness tracking',
                'category_id' => 18,
                'supplier_id' => 2,
                'brand' => 'Apple',
                'model' => 'MRY33',
                'cost_price' => 19500.00,
                'selling_price' => 24990.00,
                'markup_percentage' => 28.15,
                'tax_rate' => 12.00,
                'stock_quantity' => 18,
                'reorder_level' => 6,
                'max_stock_level' => 30,
                'unit_of_measure' => 'piece',
                'weight' => 0.051,
                'dimensions' => '45 x 38 x 10.7 mm',
                'image_url' => '/images/products/apple-watch-s9.jpg',
                'is_active' => true,
                'is_serialized' => true,
                'warranty_period' => 12,
            ],
            [
                'sku' => 'SAMSUNG-WATCH6-BLK',
                'barcode' => '8806094993530',
                'name' => 'Samsung Galaxy Watch6 Classic',
                'description' => 'Premium smartwatch with rotating bezel and health sensors',
                'category_id' => 18,
                'supplier_id' => 1,
                'brand' => 'Samsung',
                'model' => 'SM-R960',
                'cost_price' => 15000.00,
                'selling_price' => 19999.00,
                'markup_percentage' => 33.33,
                'tax_rate' => 12.00,
                'stock_quantity' => 22,
                'reorder_level' => 8,
                'max_stock_level' => 40,
                'unit_of_measure' => 'piece',
                'weight' => 0.059,
                'dimensions' => '46.5 x 46.5 x 10.9 mm',
                'image_url' => '/images/products/galaxy-watch6.jpg',
                'is_active' => true,
                'is_serialized' => true,
                'warranty_period' => 12,
            ],
        ];

        foreach ($products as $product) {
            DB::table('products')->insert(array_merge($product, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
